### PR TITLE
Adding clamp and lerp functions to standard library

### PR DESCRIPTION
**Pull request by Add00**
Hello, 

Hello, I've really enjoyed using Toylang, and I've been integrating it into my own program. I noticed that the standard library could benefit from having two additional functions, so I took the liberty to add them.

`clamp(value, min, max)` constrains `value` to within the range defined by `min` and `max`

`lerp(start, end, amount)` linear interpolates from `start` to `end` by the `amount`

I'm still learning C, so I apologize if there are any mistakes in my implementation. I've tested the functions with various scenarios, but additional testing and feedback would be greatly appreciated!

Thank you for considering my contribution.

### CODE REVIEW

**Comment by Ratstail91** [comment]
Thank you very much @Add00! 

I'm going to tweak the layout of these slightly (just the order of a few things, for consistency), and I'll write some tests and add them to the test suite for you.

**Comment by Ratstail91** [comment]
These functions are now documented.

**Comment by Add00** [comment]
Thanks, I didn't notice the test suite nor documentation. I'll be sure to add some tests and docs next time, as I'm currently working on implementing some trigonometric functions.

**Comment by Ratstail91** [comment]
Fantastic, thank you! I'll make sure everything is in line after a merge anyway, so don't sweat the small discrepencies.

If there's enough mathematic functions added, it might make sense to split them off into their own library.

**Pull request merged**
