### PR TITLE
 Adding a fileio library to toy 

### PR DESCRIPTION
**Pull request by Add00**
This has taken a lot longer then I thought it would, but I feel the fileio library is now in a usable state. I've also added a new example program to the `scripts` directory which show cases how to use read and write operations to the terminal.

### Constants
- `MAX_FILENAME_SIZE` represents the longest allowed filename, passing longer names to `open` will result in an error.
- `MAX_FILES_OPEN` the max number of concurrent files that can be open at the same time.
- `END_OF_FILE` represents the `EOF` character.

### Global Variables

- `input: opaque:file`
  - Represents the standard in.
- `output: opaque:file`
  - Represents the standard out.

I am open to better name suggestions since `input` and `output` are also common variable names. 

### Access

- `open(filename: string, mode: string): opaque:file | null` 
  - `filename` should be less then `MAX_FILENAME_SIZE`, and be located in the drive system.
  - `mode` can be one of `r`, `w`, `a`, `r+`, `w+`, `a+`, see [file access flags](https://en.cppreference.com/w/c/io/fopen) for more information.
  - Returns a file object on a successful opening.
  - Returns null if the file cannot be opened.
 - `close(): bool`
   - Closes the file stream and returns false if an error happens, true otherwise.
   - Method must be called on a variable of type `opaque:file`.

### Operations

All operations can only be called on an object of type `opaque:file`.

- `read(value: type): type`
  - `value` must be a literal type, such as `int`, `float`, `string`. It is also the type that of the value that should be read from the file.
  - Reading a `string` is greedy, it will attempt to read the largest possible string, up to the max toy string size.
  - Returns null if an invalid type is passed in, otherwise it will return the same type as `value`.
- `write(value: any): bool`
  - `value` must be a literal type, such as `int`, `float`, `string`. The value is then written to the file stream.
  - Returns a boolean representing the success of the operation.
- `rename(newName: string): bool` 
  - Changes the current name of the file to `newName`.
  - `newName` must also follow drive system. 
  - Returns true if it succeeds, false otherwise.
- `seek(origin: string, offset: int): bool`
  - Changes the current position in the file. 
  - `origin` the starting place of the seek operation can be one of: `bgn`, `cur`, `end`.
  - `offset` how many bytes to move the file position.
  - Returns true if the operation succeeds, false otherwise.

### Accessors

All accessors can only be called on an object of type `opaque:file`.

- `error(): bool`
  - Returns true if the file has an error false otherwise.
- `completed(): bool`
  - Returns true if the position in the file is at the end, otherwise false.
- `position(): int`
  - Returns the current position in the file.
  - Returns `INT_MAX` if the position in the file is greater then what can be stored in an integer.
- `size(): int`
  -  Returns the size of the file in bytes.
  -  Returns `INT_MAX` if the size of the file is greater then what can be stored in an integer.
- `mode(): string`
  - Returns the current mode of the file object. 

### Sanitation Test
16 bytes are still never deallocated. I'm having trouble finding where they are allocated.
image

### Mingw-32 Test
I don't have a windows computer at the moment so, I can really test this at the moment.

Thank you for taking the time to read this!

### CODE REVIEW

**Comment by Ratstail91** [comment]
OK, so here's a few quick notes:

* The error messages could be slightly better, such as printing out what the incorrect argument provided was ("Incorrect argument type passed to open (unrecognized yaddah yaddah")
* I'm a little iffy about stripping the strings right back to C-strings for the "createToyFile" arguments
* `valueLiteral` in `nativeRead` should be called `typeLiteral`, otherwise it's confusing
* You used a constant of 900 in `nativeRead`, rather than the correct TOY_OPAQUE_TAG thing, line 185
* why can't you read a boolean?
* line 197 - ALWAYS USE THE MACROS such as `TOY_AS_TYPE(typeLiteral).typeOf`
* fscanf is capable of failing - make sure you account for that
* 274 - should be checking if it's a type, not if it's null
* 289 - again, you checked against a constant for the tag instead of a macro
* 300 - please keep consistent indentation for this switch case
* 300 - again, not how you're supposed to get a type literal's type (this should be an error?)
* 367 - constant again
* 748 - TOY_IS_INTEGER
* It's interesting that you added some helper functions for declaring variables, but not sure I would've done it quite like that

This is an early morning review, so I'm still have asleep, so I've definitely missed stuff. But you should follow some of the guides here, and try and track down that error as well (looks like it's something in the literal cache that is being copied, but not freed somewhere - a process of elimination would help).

If you need some help, feel free to ask. 

P.S. Good job so far!

**Comment by Add00** [comment]
Thanks so much for the feedback! I'll let you know if I need any help.

**Comment by Ratstail91** [comment]
@Add00 You've got a "leak" - check the valgrind output - about 113 bytes aren't being cleaned up (they're still accessible though).

**Comment by Add00** [comment]
Thanks to your suggestion I was able to fix the sanitized error. I've also added reading and writing for boolean values. Though I can't seem to figure out how to pass the mingw32 test, but I think it has something to do with the line/file endings potentially?

**Comment by Ratstail91** [comment]
```
{
    var reader = open(PATH, "r+");
    assert reader != null, "open failed on read extended mode";

    assert reader.write("writen text") == true, "write in read extended failed";

    var result = reader.read(string);
    assert (result == "d!\n" || result == "d!\\r\n"), "read in read extended failed";

    reader.close();
    reset();
}```

Try printing `result` after the read, to see what it actually is.

**Comment by Add00** [comment]
I've updated the close method to cleanup the remaining 113 bytes. However, I don't think this should be recommended for regular programs. Since it removes the input and output files which will no longer be accessible from that point. Meaning writes and reads to the terminal will fail.

**Comment by Ratstail91** [comment]
I wanna have a good look at this when it's ready - no pressure.

**Comment by Add00** [comment]
Thanks, I wanted to add a few more tests before marking it ready for review. Unfortunately, I couldn't figure out the mingw32 issue which is quite annoying, but if you have any advice for that please let me know.

**Comment by Ratstail91** [comment]
I'll have a thorough look over the next couple days - it's been a long week lol.

**Comment by Add00** [comment]
No worries, take your time. There is no rush for this to be added.

**Comment by Ratstail91** [comment]
I promise I'll look at these tomorrow - weekend was NOT relaxing lol.

**Comment by Ratstail91** [comment]
@Add00 OK, so I've reviewed the code, and spent some time hunting down the error - it seems to be caused by the way the different platforms handle end of file characters (and possible carriage return characters). There's no way we can fix this - our best bet is possibly to work around it.

That being said, here's a few things I'd change:

* I think reading a string should actually require a terminating character or condition?
* It might be a good idea to handle only strings, but I'm not sure (I'd personally just write the libs as needed)
* Different test sections should operate on different test files
* Overall the code is messy - it needs to be cleaned up before I'm happy with it

You can see some of my efforts in https://github.com/Ratstail91/Toy/tree/Add00-main, and in the actions tab.

My final thoughts:

File management on multiple platforms is a PITA, so I'm not surprised you've had trouble with it. I wouldn't blame you if you wanted to give up at this point and try something else.

Thomas Edison failed 10,000 times before inventing the lightbulb - but when asked, he simply said that he found 10,000 ways how to not make a lightbulb. Try a different approach if you want to continue on this.

**Comment by Add00** [comment]
> I think reading a string should actually require a terminating character or condition?

Yeah, I agree I think reading until the `\n` character would be better then the current solution.

> It might be a good idea to handle only strings, but I'm not sure (I'd personally just write the libs as needed)

> Different test sections should operate on different test files

> Overall the code is messy - it needs to be cleaned up before I'm happy with it

I know it's messy, but I've been starring at this code for too long now. To see which parts are unorganized, could you provide some examples?

**Comment by Ratstail91** [comment]
Hey, I'm still alive - just been stressing over IRL stuff, so everything here took a back-seat.

I'll try getting to this issue this week.

**Comment by Add00** [comment]
Take as much time as you need. There really is no rush for this

**Comment by Ratstail91** [comment]
Closing this as stale.

I want to do a rewrite, to bring Toy to version 2. I'll post the details elsewhere.

**Pull request closed without merging**
