### PR TITLE
Adding a math library to toy

### PR DESCRIPTION
**Pull request by Add00**
Hello,

I've added a new library called `math` which uses C's math library to provide some more advanced math utilities for toy programs. I've also added a test script with numerous tests for the functions, and added the library to be imported by the REPL. I did have to make a minor change by adding the `-lm` tag to the make file to get the code to compile. However, I've never used make before this, so if I messed something up, please let me know.

**Common**
- `mod(x, y)`: Returns the modulus or remainder of dividing `x` by `y`.

**Power**
- `pow(x, y)`: Returns `x` to the power of `y`.
- `sqrt(x)`: Returns the square root of `x`.
- `qbrt(x)`: Returns the cube root of `x`.
- `hypot(x, y)`: Returns the length of the hypotenuse assuming `x` and `y` are the legs in a right-angle triangle.

**Trigonometric**
- `toRad(d)`: Converts degrees into radians.
- `toDeg(r)`: Converts radians into degrees.
- `sin(x)`: Returns the sine of `x`.
- `cos(x)`: Returns the cosine of `x`.
- `tan(x)`: Returns the tangent of `x`.
- `asin(x)`: Returns the arc sine of `x`.
- `acos(x)`: Returns the arc cosine of `x`.
- `atan(x)`: Returns the arc tangent of `x`.

**Comparison**
- `isnan(x)`: Returns true if `x` is NaN and false otherwise.
- `floatCompare(x, y)`: Returns true if `x` is approximately equal to `y`.

**Constants**
- `PI`: Represents the ratio of a circle's circumference to its diameter.
- `E`: Represents Euler's number, the base of natural logarithms.
- `EPSILON`: Represents the acceptable amount of approximation error for floats.
- `NAN`: Represents not a number, often returned when a calculation is impossible e.g. `sqrt(-1)`
- `INFINITY`: Represents the largest possible float type.

I believe this update will enhance the functionality and utility of toy program. If you encounter any issues or have any feedback, please don't hesitate to let me know.

### CODE REVIEW

**Comment by Add00** [comment]
Looks like their might be something wrong with aliasing imports since the checks fail less when I comment out these lines
image

**Comment by Ratstail91** [comment]
OK, a few notes:

* You missed a few instances of `Toy_freeLiteral` calls which, while not totally necessary, are needed for consistency (I might add a way to omit them at build time in future for speed purposes, IDK). For example, at lib_math.c, line 88, you're only freeing `xLiteral` and not `yLiteral`. Make sure every literal gets freed on every possible execution path.
* `mod` is a little redundant, as Toy supports the modulo operation with the `%` operator.
* A few naming tweaks: `checkIsNaN()`, `toRadians()`, `toDegrees()`, `epsilionCompare()`, etc.
* lib_math.c, line 792: this type should be `TOY_LITERAL_ANY`, since the alias dictionary isn't just string:function anymore.
* If you check the diff, you've accidentally deleted some lines from lib_standard.c, which is why the checks are failing.
* You need to make sure that `math.toy` is actually being executed in the tests - I can tell it isn't, because you need to add a reference to it within `test_interpreter.c`, probably at line 136.

On the whole, this is a good start. If you can address these issues, I'll review it again.

P.S. `-lm` is simply because math.h isn't part of the C standard after all, but that's fine because every compiler supports it anyway.

**Comment by Add00** [comment]
Thank you so much, for your feedback! I knew something was off but I could not figure it out. Now that I've implemented your suggestions it passes the checks.

**Comment by Ratstail91** [comment]
(I must've suggested the wrong spot for where to invoke `math.toy` - good catch!)

Congratulations on the merge! I'm super happy with how all of this looks. Will you be expanding it in future, or do you have any other ideas? I'll open up a discussion for ideas and such.

**Comment by Add00** [comment]
I think the math library could benefit from some logarithmic functions, but other then that I don't see what else it could need. As for new ideas, I think exposing the `<stdio.h>` header through an io library could be useful since then toy programs could be interactive. Though I know toy is not intended to operate on its own, so maybe that is unnecessary? I also think I could use [FastNoiseLite](https://github.com/Auburn/FastNoiseLite/tree/master) to implement a noise library which could be very useful random number generation, and game programs. 

Those are my ideas currently, what do you think?

**Comment by Ratstail91** [comment]
Jump over here https://github.com/Ratstail91/Toy/discussions/95

**Pull request merged**
